### ISSUE TITLE
What happened to PPBrowser?

### ISSUE THREAD

**Issue by khinsen** [moosetechnology/PetitParser#37]
The PetitParser chapter from "Deep into Pharo" discusses `PPBrowser`, which looks like a very nice tool but seems to be no longer part of the distribution. Do I have to get it separately now? If so, from where? Or has it been renamed?

**Comment by jecisc** [comment]
Hello,

IIRC, PPBrowser is part of PetitGUI that is not loaded by default.

You can load it by loading the group `ParserIDE` instead of the group default.

```Smalltalk
Metacello new
   baseline: 'PetitParser';
   repository: 'github://moosetechnology/PetitParser/src';
   load: 'PetitIDE'.
```

**Comment by jecisc** [comment]
I let you close the issue if it works for you.

**Comment by khinsen** [comment]
Thanks!  It's `ParserIDE` in the `Metacello` invocation, not `PetitIDE`, but with that change it works fine. And it's a nice tool indeed!
