### ISSUE TITLE
Incorrect error handling in PPXmlParser

### ISSUE THREAD

**Issue by khinsen** [moosetechnology/PetitParser#38]
Running the following code 
```
| p |
p := PPXmlParser new.
p parse: '<a><b></c></a>'
```
in a Pharo 7 playground leads to the error "#noteFailure: was sent to nil".

This happens because`PPXmlGrammar>>element` creates a `PPFailure` object with context set to `nil`.

**Comment by juliendelplanque** [comment]
Hello, this parser is there as a demo. It is not encouraged to use it in production.

You should use the XML parser loaded by the following script instead:

```
Metacello new
	smalltalkhubUser: 'Pharo' project: 'MetaRepoForPharo70';
	configuration: 'XMLParser';
	version: #stable;
	load.
```

Thus, I will just close this issue...

Cheers,

Julien

**Comment by khinsen** [comment]
I'd rather suggest that you remove this demo parser if you do not want to fix it. A demo that crashes is a bad demo.

In fact, I never had the intention to use this parser, I merely looked at its code for inspiration about... failure handling. Which is exactly the part that doesn't work.
