### ISSUE TITLE
Fix ConfigurationOf in Pharo Projects Catalog

### ISSUE THREAD

**Issue by kursjan** [moosetechnology/PetitParser#52]
I got a report from a user that PetitParser does not load to Pharo8:

> Loading PetitParser from the Pharo Project Catalog causes an error & fails.

Is it expected to work?

**Comment by juliendelplanque** [comment]
The catalog probably load the Smalltalkhub version as we never updated it after migration on GitHub as far as I know.

**Comment by juliendelplanque** [comment]
To check the status of PP on Pharo 8, I just created this PR #53 . Let us see how it goes. :-)

**Comment by juliendelplanque** [comment]
Tests run correctly on P8. So it is definitely the configuration in Pharo catalog.
We will see if we can fix it.

**Comment by badetitou** [comment]
We will not update the catalog in the future. I think it is clear now.
Let's close this issue
